// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphQLMockInputTypeJs from "../GraphQLMockInputType.js";

var make = GraphQLMockInputTypeJs.GraphQLPreview;

export {
  make ,
  
}
/* make Not a pure module */
