// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";

function parseExn(s) {
  if (Uuid.validate(s)) {
    return s;
  }
  throw {
        RE_EXN_ID: "Failure",
        _1: "ParseExn",
        Error: new Error()
      };
}

export {
  parseExn ,
  
}
/* uuid Not a pure module */
