// Generated by ReScript, PLEASE EDIT WITH CARE
/* @generated */

import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";

var Types = {};

var fragmentConverter = {"__root":{"name":{"n":""},"id":{"n":""},"description":{"n":""},"downloads_lastMonth":{"n":""}}};

function convertFragment(v) {
  return RescriptRelay.convertObj(v, fragmentConverter, undefined, undefined);
}

var Internal = {
  fragmentConverter: fragmentConverter,
  fragmentConverterMap: undefined,
  convertFragment: convertFragment
};

var Utils = {};

var node = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PackageInfo_npmPackage",
  "selections": [
    {
      "alias": null,
      "args": null,
      "kind": "ScalarField",
      "name": "name",
      "storageKey": null
    },
    {
      "alias": null,
      "args": null,
      "kind": "ScalarField",
      "name": "description",
      "storageKey": null
    },
    {
      "alias": null,
      "args": null,
      "kind": "ScalarField",
      "name": "id",
      "storageKey": null
    },
    {
      "alias": null,
      "args": null,
      "concreteType": "NpmPackageDownloadData",
      "kind": "LinkedField",
      "name": "downloads",
      "plural": false,
      "selections": [
        {
          "alias": null,
          "args": null,
          "concreteType": "NpmPackageDownloadPeriodData",
          "kind": "LinkedField",
          "name": "lastMonth",
          "plural": false,
          "selections": [
            {
              "alias": "downloadCount",
              "args": null,
              "kind": "ScalarField",
              "name": "count",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "NpmPackage",
  "abstractKey": null
};

export {
  Types ,
  Internal ,
  Utils ,
  node ,
  
}
/* RescriptRelay Not a pure module */
