// Generated by ReScript, PLEASE EDIT WITH CARE
/* @generated */

import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";

var Types = {};

var wrapResponseConverter = {"__root":{"oneGraph_updateChainScript":{"n":""},"oneGraph_updateChainScript_script":{"f":""}}};

function convertWrapResponse(v) {
  return RescriptRelay.convertObj(v, wrapResponseConverter, undefined, null);
}

var responseConverter = {"__root":{"oneGraph_updateChainScript":{"n":""},"oneGraph_updateChainScript_script":{"f":""}}};

function convertResponse(v) {
  return RescriptRelay.convertObj(v, responseConverter, undefined, undefined);
}

var variablesConverter = {"OneGraphUpdateChainScriptInput":{"source":{"r":"OneGraphUpdateChainScriptSourceArg"}},"__root":{"input":{"r":"OneGraphUpdateChainScriptInput"}}};

function convertVariables(v) {
  return RescriptRelay.convertObj(v, variablesConverter, undefined, undefined);
}

var Internal = {
  wrapResponseConverter: wrapResponseConverter,
  wrapResponseConverterMap: undefined,
  convertWrapResponse: convertWrapResponse,
  responseConverter: responseConverter,
  responseConverterMap: undefined,
  convertResponse: convertResponse,
  convertWrapRawResponse: convertWrapResponse,
  convertRawResponse: convertResponse,
  variablesConverter: variablesConverter,
  variablesConverterMap: undefined,
  convertVariables: convertVariables
};

function make_oneGraphUpdateChainScriptSourceArg(concurrentSource, textualSource) {
  return {
          concurrentSource: concurrentSource,
          textualSource: textualSource
        };
}

function make_oneGraphUpdateChainScriptInput(source, id) {
  return {
          source: source,
          id: id
        };
}

function makeVariables(input) {
  return {
          input: input
        };
}

function make_response_oneGraph_updateChainScript_script(param) {
  
}

function make_response_oneGraph_updateChainScript(script) {
  return {
          script: script
        };
}

function make_response_oneGraph(updateChainScript, param) {
  return {
          updateChainScript: updateChainScript
        };
}

function makeOptimisticResponse(oneGraph) {
  return {
          oneGraph: oneGraph
        };
}

var Utils = {
  make_oneGraphUpdateChainScriptSourceArg: make_oneGraphUpdateChainScriptSourceArg,
  make_oneGraphUpdateChainScriptInput: make_oneGraphUpdateChainScriptInput,
  makeVariables: makeVariables,
  make_response_oneGraph_updateChainScript_script: make_response_oneGraph_updateChainScript_script,
  make_response_oneGraph_updateChainScript: make_response_oneGraph_updateChainScript,
  make_response_oneGraph: make_response_oneGraph,
  makeOptimisticResponse: makeOptimisticResponse
};

var node = ((function(){
var v0 = [
  {
    "defaultValue": null,
    "kind": "LocalArgument",
    "name": "input"
  }
],
v1 = [
  {
    "kind": "Variable",
    "name": "input",
    "variableName": "input"
  }
];
return {
  "fragment": {
    "argumentDefinitions": (v0/*: any*/),
    "kind": "Fragment",
    "metadata": null,
    "name": "ScriptEditor_OneGraphMutation",
    "selections": [
      {
        "alias": null,
        "args": null,
        "concreteType": "OneGraphMutation",
        "kind": "LinkedField",
        "name": "oneGraph",
        "plural": false,
        "selections": [
          {
            "alias": null,
            "args": (v1/*: any*/),
            "concreteType": "OneGraphUpdateChainScriptResponsePayload",
            "kind": "LinkedField",
            "name": "updateChainScript",
            "plural": false,
            "selections": [
              {
                "alias": null,
                "args": null,
                "concreteType": "OneGraphSourceFile",
                "kind": "LinkedField",
                "name": "script",
                "plural": false,
                "selections": [
                  {
                    "args": null,
                    "kind": "FragmentSpread",
                    "name": "ScriptEditor_source"
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation",
    "abstractKey": null
  },
  "kind": "Request",
  "operation": {
    "argumentDefinitions": (v0/*: any*/),
    "kind": "Operation",
    "name": "ScriptEditor_OneGraphMutation",
    "selections": [
      {
        "alias": null,
        "args": null,
        "concreteType": "OneGraphMutation",
        "kind": "LinkedField",
        "name": "oneGraph",
        "plural": false,
        "selections": [
          {
            "alias": null,
            "args": (v1/*: any*/),
            "concreteType": "OneGraphUpdateChainScriptResponsePayload",
            "kind": "LinkedField",
            "name": "updateChainScript",
            "plural": false,
            "selections": [
              {
                "alias": null,
                "args": null,
                "concreteType": "OneGraphSourceFile",
                "kind": "LinkedField",
                "name": "script",
                "plural": false,
                "selections": [
                  {
                    "alias": null,
                    "args": null,
                    "kind": "ScalarField",
                    "name": "id",
                    "storageKey": null
                  },
                  {
                    "alias": null,
                    "args": null,
                    "kind": "ScalarField",
                    "name": "filename",
                    "storageKey": null
                  },
                  {
                    "alias": null,
                    "args": null,
                    "kind": "ScalarField",
                    "name": "language",
                    "storageKey": null
                  },
                  {
                    "alias": null,
                    "args": null,
                    "kind": "ScalarField",
                    "name": "concurrentSource",
                    "storageKey": null
                  },
                  {
                    "alias": null,
                    "args": null,
                    "kind": "ScalarField",
                    "name": "textualSource",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "params": {
    "cacheID": "6ff2dd5bc39cfc264de27e70140fa1f7",
    "id": null,
    "metadata": {},
    "name": "ScriptEditor_OneGraphMutation",
    "operationKind": "mutation",
    "text": "mutation ScriptEditor_OneGraphMutation(\n  $input: OneGraphUpdateChainScriptInput!\n) {\n  oneGraph {\n    updateChainScript(input: $input) {\n      script {\n        ...ScriptEditor_source\n      }\n    }\n  }\n}\n\nfragment ScriptEditor_source on OneGraphSourceFile {\n  id\n  filename\n  language\n  concurrentSource\n  textualSource\n}\n"
  }
};
})());

export {
  Types ,
  Internal ,
  Utils ,
  node ,
  
}
/* node Not a pure module */
