// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Icons from "../Icons.mjs";
import * as React from "react";
import * as $$Navigator from "../bindings/Navigator.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function AudioChat(Props) {
  var match = React.useState(function () {
        return {
                audioLevel: 0,
                audioStream: /* Empty */0
              };
      });
  var setState = match[1];
  var onStartAudio = function (param) {
    return Belt_Option.forEach($$Navigator.$$MediaDevices.getUserAudio(undefined), (function (promise) {
                  var __x = promise.then(function (stream) {
                        Curry._1(setState, (function (oldState) {
                                return {
                                        audioLevel: oldState.audioLevel,
                                        audioStream: {
                                          _0: stream,
                                          [Symbol.for("name")]: "Loaded"
                                        }
                                      };
                              }));
                        return Promise.resolve((console.log("Got stream: ", stream), undefined));
                      });
                  __x.catch(function (err) {
                        return Promise.resolve((console.warn("Unable to get audio stream: ", err), undefined));
                      });
                  
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Icons.Volume.Auto.make, {
                  color: "red",
                  level: match[0].audioLevel,
                  onClick: onStartAudio
                }), React.createElement(Icons.Volume.Auto.make, {
                  color: "#662299",
                  level: 99,
                  onClick: onStartAudio
                }), React.createElement(Icons.Volume.Auto.make, {
                  level: 10,
                  onClick: onStartAudio
                }));
}

var make = AudioChat;

export {
  make ,
  
}
/* Icons Not a pure module */
