// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as React from "react";
import * as Graphql from "graphql";
import * as GraphQLJs from "../bindings/GraphQLJs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.mjs";
import * as BsReactMonaco from "../bindings/BsReactMonaco.js";
import GraphiqlExplorer from "graphiql-explorer";

var GraphiQLExplorer = {};

function BlockEditor(Props) {
  var schema = Props.schema;
  var initialBlock = Props.block;
  var onClose = Props.onClose;
  var onSave = Props.onSave;
  var match = React.useState(function () {
        return initialBlock;
      });
  var setBlock = match[1];
  var block = match[0];
  React.useEffect((function () {
          Curry._1(setBlock, (function (param) {
                  return initialBlock;
                }));
          
        }), [initialBlock.body]);
  var updateBlock = function (newOperationDoc) {
    var opDoc = Graphql.parse(newOperationDoc);
    var title = Belt_Option.getWithDefault(Belt_Array.get(GraphQLJs.operationNames(opDoc), 0), "Untitled");
    return Curry._1(setBlock, (function (oldBlock) {
                  return {
                          id: oldBlock.id,
                          title: title,
                          description: oldBlock.description,
                          body: newOperationDoc,
                          kind: oldBlock.kind,
                          contributedBy: oldBlock.contributedBy,
                          services: oldBlock.services
                        };
                }));
  };
  var explorer = React.createElement("div", {
        className: "graphiql-container w-full"
      }, React.createElement(GraphiqlExplorer, {
            schema: schema,
            explorerIsOpen: true,
            query: block.body,
            width: "100%",
            height: "100%",
            onEdit: updateBlock
          }));
  var editor = React.createElement(BsReactMonaco.Editor.make, {
        height: "100%",
        value: block.body,
        className: "flex-grow h-full",
        language: "graphql",
        theme: "vs-dark",
        options: {
          minimap: {
            enabled: false
          }
        },
        onChange: (function (newOperationDoc, param) {
            return updateBlock(newOperationDoc);
          })
      });
  return React.createElement("div", {
              className: "flex w-full flex-col"
            }, React.createElement("div", {
                  className: "flex flex-grow flex-row h-full"
                }, explorer, editor), React.createElement("div", {
                  className: "w-full ml-auto flex"
                }, React.createElement("button", {
                      className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex-grow",
                      onClick: (function (param) {
                          return Curry._2(onSave, block, block);
                        })
                    }, "Save"), React.createElement("button", {
                      className: "bg-transparent hover:bg-gray-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded flex-grow",
                      onClick: (function (param) {
                          return Curry._1(onClose, undefined);
                        })
                    }, "Cancel")));
}

var make = BlockEditor;

export {
  GraphiQLExplorer ,
  make ,
  
}
/* react Not a pure module */
