// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RelayRuntime from "relay-runtime";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as Hooks from "react-relay/hooks";
import * as RescriptRelay_Internal from "rescript-relay/src/RescriptRelay_Internal.mjs";
import * as ChainViewer_chain_graphql from "../__generated__/ChainViewer_chain_graphql.mjs";
import * as ChainViewer_Subscription_graphql from "../__generated__/ChainViewer_Subscription_graphql.mjs";

function use(fRef) {
  var data = Hooks.useFragment(ChainViewer_chain_graphql.node, fRef);
  return RescriptRelay_Internal.internal_useConvertedValue(ChainViewer_chain_graphql.Internal.convertFragment, data);
}

function useOpt(opt_fRef) {
  var fr = opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined;
  var nullableFragmentData = Hooks.useFragment(ChainViewer_chain_graphql.node, fr !== undefined ? Js_null_undefined.fromOption(Caml_option.some(Caml_option.valFromOption(fr))) : null);
  var data = (nullableFragmentData == null) ? undefined : Caml_option.some(nullableFragmentData);
  return RescriptRelay_Internal.internal_useConvertedValue((function (rawFragment) {
                if (rawFragment !== undefined) {
                  return ChainViewer_chain_graphql.Internal.convertFragment(rawFragment);
                }
                
              }), data);
}

var OneGraphChainViewerFragment = {
  Types: undefined,
  use: use,
  useOpt: useOpt
};

function subscribe(environment, variables, onCompleted, onError, onNext, updater, param) {
  var tmp = {
    subscription: ChainViewer_Subscription_graphql.node,
    variables: ChainViewer_Subscription_graphql.Internal.convertVariables(variables)
  };
  if (onCompleted !== undefined) {
    tmp.onCompleted = Caml_option.valFromOption(onCompleted);
  }
  if (onError !== undefined) {
    tmp.onError = Caml_option.valFromOption(onError);
  }
  var tmp$1 = onNext !== undefined ? (function (r) {
        return Curry._1(onNext, ChainViewer_Subscription_graphql.Internal.convertResponse(r));
      }) : undefined;
  if (tmp$1 !== undefined) {
    tmp.onNext = Caml_option.valFromOption(tmp$1);
  }
  var tmp$2 = updater !== undefined ? (function (store, r) {
        return Curry._2(updater, store, ChainViewer_Subscription_graphql.Internal.convertResponse(r));
      }) : undefined;
  if (tmp$2 !== undefined) {
    tmp.updater = Caml_option.valFromOption(tmp$2);
  }
  return RelayRuntime.requestSubscription(environment, tmp);
}

var Subscription_makeVariables = ChainViewer_Subscription_graphql.Utils.makeVariables;

var Subscription = {
  makeVariables: Subscription_makeVariables,
  Types: undefined,
  subscribe: subscribe
};

function ChainViewer(Props) {
  var oneGraphAppPackageRef = Props.oneGraphAppPackageRef;
  var chain = use(oneGraphAppPackageRef);
  React.useState(function () {
        
      });
  return React.createElement("div", undefined, chain.name);
}

var make = ChainViewer;

export {
  OneGraphChainViewerFragment ,
  Subscription ,
  make ,
  
}
/* react Not a pure module */
