// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as Hooks from "react-relay/hooks";
import * as RescriptRelay_Internal from "rescript-relay/src/RescriptRelay_Internal.mjs";
import * as ChainViewer_oneGraphAppPackageChain_graphql from "../__generated__/ChainViewer_oneGraphAppPackageChain_graphql.mjs";

function use(fRef) {
  var data = Hooks.useFragment(ChainViewer_oneGraphAppPackageChain_graphql.node, fRef);
  return RescriptRelay_Internal.internal_useConvertedValue(ChainViewer_oneGraphAppPackageChain_graphql.Internal.convertFragment, data);
}

function useOpt(opt_fRef) {
  var fr = opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined;
  var nullableFragmentData = Hooks.useFragment(ChainViewer_oneGraphAppPackageChain_graphql.node, fr !== undefined ? Js_null_undefined.fromOption(Caml_option.some(Caml_option.valFromOption(fr))) : null);
  var data = (nullableFragmentData == null) ? undefined : Caml_option.some(nullableFragmentData);
  return RescriptRelay_Internal.internal_useConvertedValue((function (rawFragment) {
                if (rawFragment !== undefined) {
                  return ChainViewer_oneGraphAppPackageChain_graphql.Internal.convertFragment(rawFragment);
                }
                
              }), data);
}

var OneGraphChainViewerFragment = {
  Types: undefined,
  use: use,
  useOpt: useOpt
};

function ChainViewer(Props) {
  var oneGraphAppPackageRef = Props.oneGraphAppPackageRef;
  var chain = use(oneGraphAppPackageRef);
  React.useState(function () {
        
      });
  return React.createElement("div", undefined, chain.name);
}

var make = ChainViewer;

export {
  OneGraphChainViewerFragment ,
  make ,
  
}
/* react Not a pure module */
