// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext(/* Empty */0);

var provider = context.Provider;

function ConnectionContext$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: ConnectionContext$Provider
};

export {
  context ,
  Provider ,
  
}
/* context Not a pure module */
