// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card.js";
import * as Chain from "../Chain.js";
import * as Comps from "./Comps.js";
import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as Icons from "../Icons.js";
import * as React from "react";
import * as Js_dict from "bs-platform/lib/es6/js_dict.mjs";
import * as Graphql from "graphql";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.mjs";
import * as GraphQLJs from "../bindings/GraphQLJs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";
import * as OneGraphRe from "../OneGraphRe.js";
import * as Typescript from "typescript";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.mjs";
import * as Caml_option from "bs-platform/lib/es6/caml_option.mjs";
import * as OneGraphAuth from "../bindings/OneGraphAuth.js";
import * as BsReactMonaco from "../bindings/BsReactMonaco.js";
import * as OnegraphAuth from "onegraph-auth";
import * as Belt_SetString from "bs-platform/lib/es6/belt_SetString.mjs";
import * as GraphQLFormJs from "../GraphQLForm.js";
import CopyToClipboard from "copy-to-clipboard";
import * as QuickjsEmscripten from "quickjs-emscripten";
import * as GraphQLMockInputTypeJs from "../GraphQLMockInputType.js";

var AdvancedMode = {
  enabled: false
};

var Clipboard = {};

var make = GraphQLMockInputTypeJs.GraphQLPreview;

var GraphQLPreview = {
  make: make
};

function formInput(prim, prim$1, prim$2, prim$3) {
  return GraphQLFormJs.formInput(prim, prim$1, prim$2, prim$3);
}

function transpileFullChainScript(chain) {
  var baseTranspiled = Typescript.transpile(chain.script, {
        target: "ES2020"
      });
  var allCalls = Belt_Array.map(chain.requests, (function (request) {
            var requestCalls = Belt_Array.keepMap(request.variableDependencies, (function (varDep) {
                    var _argDep = varDep.dependency;
                    if (_argDep.TAG === /* ArgumentDependency */0) {
                      return Chain.callForVariable(request, varDep.name);
                    }
                    
                  }));
            return requestCalls.join("\n\n");
          })).join("\n\n");
  return baseTranspiled + "\n\n" + allCalls;
}

function patchRequestArgDeps(request) {
  var variableDependencies = Belt_Array.map(request.variableDependencies, (function (varDep) {
          var argDep = varDep.dependency;
          var dependency;
          if (argDep.TAG === /* ArgumentDependency */0) {
            var argDep$1 = argDep._0;
            var requestScriptName = Chain.requestScriptNames(request).functionName;
            var functionFromScript = requestScriptName + "_" + varDep.name;
            var newArgDep_maxRecur = argDep$1.maxRecur;
            var newArgDep_ifMissing = argDep$1.ifMissing;
            var newArgDep_ifList = argDep$1.ifList;
            var newArgDep_fromRequestIds = request.dependencyRequestIds;
            var newArgDep_name = argDep$1.name;
            var newArgDep = {
              functionFromScript: functionFromScript,
              maxRecur: newArgDep_maxRecur,
              ifMissing: newArgDep_ifMissing,
              ifList: newArgDep_ifList,
              fromRequestIds: newArgDep_fromRequestIds,
              name: newArgDep_name
            };
            dependency = {
              TAG: 0,
              _0: newArgDep,
              [Symbol.for("name")]: "ArgumentDependency"
            };
          } else {
            dependency = argDep;
          }
          return {
                  name: varDep.name,
                  dependency: dependency
                };
        }));
  return {
          id: request.id,
          variableDependencies: variableDependencies,
          operation: request.operation,
          dependencyRequestIds: request.dependencyRequestIds
        };
}

function patchChainRequestsArgDeps(chain) {
  return Belt_Array.map(chain.requests, patchRequestArgDeps);
}

function evalRequest(schema, chain, request, requestValueCache) {
  var __x = QuickjsEmscripten.getQuickJS();
  var __x$1 = __x.then(function (quickjs) {
        var payload = Belt_Array.reduce(Belt_Array.keepMap(Belt_Array.concatMany(Belt_Array.keepMap(request.variableDependencies, (function (varDep) {
                            var argDep = varDep.dependency;
                            if (argDep.TAG === /* ArgumentDependency */0) {
                              return argDep._0.fromRequestIds;
                            }
                            
                          }))), (function (upstreamRequestId) {
                    return Belt_Array.getBy(chain.requests, (function (request) {
                                  return request.id === upstreamRequestId;
                                }));
                  })), {}, (function (acc, nextRequest) {
                var match = Js_dict.get(acc, nextRequest.id);
                if (match !== undefined) {
                  return acc;
                }
                var parsedOperation = Graphql.parse(nextRequest.operation.body);
                var definition = Belt_Array.getExn(parsedOperation.definitions, 0);
                var variables = GraphQLJs.Mock.mockOperationVariables(schema, definition);
                var results = Js_dict.get(requestValueCache, nextRequest.id);
                if (results !== undefined) {
                  acc[nextRequest.id] = {
                    variables: variables,
                    graphQLResult: Caml_option.valFromOption(results)
                  };
                  return acc;
                }
                var results$1 = Graphql.graphqlSync(schema, nextRequest.operation.body, undefined, undefined, Caml_option.some(variables));
                acc[nextRequest.id] = {
                  variables: variables,
                  graphQLResult: results$1
                };
                return acc;
              }));
        var transpiled = transpileFullChainScript(chain);
        var payload$1 = JSON.stringify(Js_dict.fromArray(Belt_Array.map(Js_dict.entries(payload), (function (param) {
                        return [
                                param[0],
                                param[1].graphQLResult
                              ];
                      }))));
        var operationDoc = request.operation.body;
        var parsedOperation = Graphql.parse(request.operation.body);
        var definition = Belt_Array.getExn(parsedOperation.definitions, 0);
        var mockedVariables = GraphQLJs.Mock.mockOperationVariables(schema, definition);
        var variables = Belt_Array.reduce(request.variableDependencies, mockedVariables, (function (acc, nextVarDependency) {
                var argDep = nextVarDependency.dependency;
                if (argDep.TAG !== /* ArgumentDependency */0) {
                  return acc;
                }
                var call = argDep._0.functionFromScript + "(" + payload$1 + ")";
                var script = transpiled + "\n\n" + call;
                var fullScript = script.replace(new RegExp("export ", "g"), "");
                var result = quickjs.evalCode(fullScript);
                acc[nextVarDependency.name] = result;
                return acc;
              }));
        var graphQLResult = Graphql.graphqlSync(schema, operationDoc, undefined, undefined, Caml_option.some(variables));
        return Promise.resolve({
                    TAG: 0,
                    _0: {
                      variables: variables,
                      graphQLResult: graphQLResult
                    },
                    [Symbol.for("name")]: "Ok"
                  });
      });
  return __x$1.catch(function (err) {
              console.warn("Error evalRequest: ", err);
              return Promise.resolve({
                          TAG: 1,
                          _0: err,
                          [Symbol.for("name")]: "Error"
                        });
            });
}

function findMissingAuthServicesFromChainResult(result) {
  try {
    var chainResults = result.data.oneGraph.executeChain.results;
    return OneGraphAuth.distinctServices(Belt_Array.concatMany(Belt_Array.map(chainResults, (function (operation) {
                          var errors;
                          try {
                            errors = Belt_Array.concatMany(Belt_Array.map(operation.result, (function (result) {
                                        return result.errors;
                                      })));
                          }
                          catch (exn){
                            errors = [];
                          }
                          return OnegraphAuth.findMissingAuthServices(errors);
                        }))));
  }
  catch (exn){
    return [];
  }
}

function internallyPatchChain(chain) {
  var transpiled = transpileFullChainScript(chain);
  var requestsWithLockedVariables = patchChainRequestsArgDeps(chain);
  return {
          name: chain.name,
          script: transpiled,
          requests: requestsWithLockedVariables,
          blocks: chain.blocks
        };
}

function transformChain(chain) {
  return Chain.compileOperationDoc(internallyPatchChain(chain));
}

function remoteChainCalls(appId, chainId, chain) {
  var compiled = Chain.compileOperationDoc(internallyPatchChain(chain));
  var targetChain = compiled.chains[0];
  var freeVariables = Belt_Array.map(targetChain.exposedVariables, (function (exposed) {
            var key = exposed.exposedName;
            var _other = exposed.upstreamType;
            var value;
            switch (_other) {
              case "Float" :
              case "Float!" :
                  value = "42.0";
                  break;
              case "Int" :
              case "Int!" :
                  value = "42";
                  break;
              case "String" :
              case "String!" :
                  value = "\"\"";
                  break;
              default:
                value = "{}";
            }
            return "\"" + key + "\": " + value;
          })).join(", ");
  var curl = "curl -X POST \"https://serve.onegraph.com/graphql?app_id=" + appId + "\" --data '{\"doc_id\": \"" + chainId + "\", \"operationName\": \"" + targetChain.operationName + "\", \"variables\": {" + freeVariables + "}}'";
  var $$fetch = "await fetch(\"https://serve.onegraph.com/graphql?app_id=" + appId + "\",\n  {\n    method: \"POST\",\n    \"Content-Type\": \"application/json\",\n    body: JSON.stringify({\n      \"doc_id\": \"" + chainId + "\",\n      \"operationName\": \"" + targetChain.operationName + "\",\n      \"variables\": {" + freeVariables + "}\n      }\n    )\n  }\n)";
  var scriptKitArgs = Belt_Array.map(targetChain.exposedVariables, (function (exposed) {
            var key = exposed.exposedName;
            var _other = exposed.upstreamType;
            var coerce;
            switch (_other) {
              case "Float" :
              case "Float!" :
                  coerce = "parseFloat(await arg(\"" + key + "\"))";
                  break;
              case "Int" :
              case "Int!" :
                  coerce = "parseInt(await arg(\"" + key + "\"))";
                  break;
              case "JSON" :
              case "JSON!" :
                  coerce = "JSON.parse(await arg(\"" + key + "\"))";
                  break;
              case "String" :
              case "String!" :
                  coerce = "await arg(\"" + key + "\")";
                  break;
              default:
                coerce = "await arg(\"" + key + "\"\")";
            }
            return "// " + exposed.upstreamType + "\nconst " + key + " = " + coerce;
          })).join("\n");
  var scriptKitVariables = Belt_Array.map(targetChain.exposedVariables, (function (exposed) {
            var key = exposed.exposedName;
            return "\"" + key + "\": " + key;
          })).join(", ");
  var scriptKit = "\n" + scriptKitArgs + "\n\nlet response = await post(\"https://serve.onegraph.com/graphql?app_id=" + appId + "\",\n  JSON.stringify(\n    {\n     \"doc_id\": \"" + chainId + "\",\n     \"operationName\": \"" + targetChain.operationName + "\",\n     \"variables\": {" + scriptKitVariables + "}\n    }\n  ) \n)\n\nconsole.log(\"Response: \", response.data)\n";
  return {
          fetch: $$fetch,
          curl: curl,
          scriptKit: scriptKit
        };
}

function transformAndExecuteChain(chain, oneGraphAuth, variables) {
  var compiled = Chain.compileOperationDoc(internallyPatchChain(chain));
  var targetChain = compiled.chains[0];
  return OneGraphRe.fetchOneGraph(oneGraphAuth, compiled.operationDoc, targetChain.operationName, variables);
}

function Inspector$Block(Props) {
  var block = Props.block;
  var onAddBlock = Props.onAddBlock;
  var match = React.useState(function () {
        return block.body;
      });
  var setOriginalContent = match[1];
  var editor = React.useRef(undefined);
  React.useEffect((function () {
          var value = Belt_Option.map(editor.current, (function (prim) {
                  return prim.getValue();
                }));
          var match = Caml_obj.caml_equal(block.body, value);
          if (value !== undefined && !match) {
            Curry._1(setOriginalContent, (function (param) {
                    return block.body;
                  }));
            Belt_Option.forEach(editor.current, (function (editor) {
                    editor.setValue(block.body);
                    
                  }));
          }
          
        }), [match[0] === block.body]);
  return React.createElement(React.Fragment, undefined, React.createElement("pre", {
                  className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200 overflow-scroll select-all"
                }, block.body), React.createElement("button", {
                  className: "w-full focus:outline-none text-white text-sm py-2.5 px-5 border-b-4 border-gray-600 rounded-md bg-gray-500 hover:bg-gray-400 m-2",
                  type: "button",
                  onClick: (function (param) {
                      return Curry._1(onAddBlock, block);
                    })
                }, "Add block to chain"));
}

var Block = {
  make: Inspector$Block
};

function Inspector$DirectVariable(Props) {
  var variable = Props.variable;
  var onVariableUpdated = Props.onVariableUpdated;
  return React.createElement("div", {
              className: ""
            }, React.createElement("form", undefined, React.createElement("label", {
                      className: "m-0"
                    }, React.createElement("div", {
                          className: "mt-1 flex rounded-md shadow-sm"
                        }, React.createElement("span", {
                              className: "inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm"
                            }, "$variableName:"), React.createElement("input", {
                              className: "block w-full px-3 text-gray-500 border border-gray-300 bg-white border-l-0 rounded-md shadow-sm focus:outline-none focus:ring-blue-300 focus:border-blue-300 sm:text-sm rounded-l-none",
                              value: variable,
                              onChange: (function ($$event) {
                                  return Curry._1(onVariableUpdated, $$event.target.value);
                                })
                            })))));
}

var DirectVariable = {
  make: Inspector$DirectVariable
};

function Inspector$DirectJSON(Props) {
  var json = Props.json;
  var onJsonUpdated = Props.onJsonUpdated;
  return React.createElement("div", {
              className: ""
            }, React.createElement("form", undefined, React.createElement("label", {
                      className: "m-0"
                    }, React.createElement("div", {
                          className: "mt-1 flex rounded-md shadow-sm"
                        }, React.createElement("span", {
                              className: "inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm"
                            }, "Raw JSON:"), React.createElement("textarea", {
                              defaultValue: JSON.stringify(json),
                              className: "block w-full px-3 text-gray-500 border border-gray-300 bg-white border-l-0 rounded-md shadow-sm focus:outline-none focus:ring-blue-300 focus:border-blue-300 sm:text-sm rounded-l-none",
                              onChange: (function ($$event) {
                                  var value = $$event.target.value;
                                  var newJson;
                                  try {
                                    newJson = Caml_option.some(JSON.parse(value));
                                  }
                                  catch (exn){
                                    newJson = undefined;
                                  }
                                  return Belt_Option.forEach(newJson, onJsonUpdated);
                                })
                            })))));
}

var DirectJSON = {
  make: Inspector$DirectJSON
};

function Inspector$ArgumentDependency(Props) {
  var argDep = Props.argDep;
  var onArgDepUpdated = Props.onArgDepUpdated;
  return React.createElement("div", undefined, React.createElement("form", undefined, React.createElement("label", {
                      className: "m-0"
                    }, React.createElement("div", {
                          className: "flex rounded-md shadow-sm"
                        }, React.createElement("span", {
                              className: "inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm"
                            }, "ifMissing:"), React.createElement("select", {
                              className: "block w-full text-gray-500 px-3 border border-gray-300 bg-white border-l-0 rounded-md shadow-sm focus:outline-none focus:ring-blue-300 focus:border-blue-300 sm:text-sm rounded-l-none m-0 pt-0 pb-0 pl-4 pr-8",
                              value: argDep.ifMissing,
                              onChange: (function ($$event) {
                                  var ifMissing = Chain.ifMissingOfString($$event.target.value);
                                  if (ifMissing.TAG === /* Ok */0) {
                                    return Curry._1(onArgDepUpdated, {
                                                functionFromScript: argDep.functionFromScript,
                                                maxRecur: argDep.maxRecur,
                                                ifMissing: ifMissing._0,
                                                ifList: argDep.ifList,
                                                fromRequestIds: argDep.fromRequestIds,
                                                name: argDep.name
                                              });
                                  }
                                  
                                })
                            }, React.createElement("option", {
                                  value: Chain.stringOfIfMissing("ERROR")
                                }, "Error"), React.createElement("option", {
                                  value: Chain.stringOfIfMissing("ALLOW")
                                }, "Allow"), React.createElement("option", {
                                  value: Chain.stringOfIfMissing("SKIP")
                                }, "Skip")))), null));
}

var ArgumentDependency = {
  make: Inspector$ArgumentDependency
};

function emptyArgumentDependency(variableName) {
  return {
          name: variableName,
          dependency: {
            TAG: 0,
            _0: {
              functionFromScript: "INITIAL_UNKNOWN",
              maxRecur: undefined,
              ifMissing: "ERROR",
              ifList: "ALL",
              fromRequestIds: [],
              name: variableName
            },
            [Symbol.for("name")]: "ArgumentDependency"
          }
        };
}

function Inspector$RequestArgument(Props) {
  var request = Props.request;
  var chain = Props.chain;
  var variableName = Props.variableName;
  var onRequestUpdated = Props.onRequestUpdated;
  var defaultRequestArgument = Props.defaultRequestArgument;
  var argDep = Belt_Option.getWithDefault(Belt_Array.getBy(request.variableDependencies, (function (argDep) {
              return argDep.name === variableName;
            })), defaultRequestArgument);
  var argDep$1 = argDep.dependency;
  if (argDep$1.TAG === /* ArgumentDependency */0) {
    return React.createElement(Inspector$ArgumentDependency, {
                request: request,
                chain: chain,
                argDep: argDep$1._0,
                onArgDepUpdated: (function (newArgDep) {
                    return Curry._1(onRequestUpdated, {
                                id: request.id,
                                variableDependencies: Belt_Array.keepMap(request.variableDependencies, (function (variableDependency) {
                                        var dependency = variableDependency.name === variableName ? ({
                                              TAG: 0,
                                              _0: newArgDep,
                                              [Symbol.for("name")]: "ArgumentDependency"
                                            }) : variableDependency.dependency;
                                        return {
                                                name: variableDependency.name,
                                                dependency: dependency
                                              };
                                      })),
                                operation: request.operation,
                                dependencyRequestIds: request.dependencyRequestIds
                              });
                  })
              });
  }
  var variable = argDep$1._0.value;
  if (variable.TAG === /* JSON */0) {
    return React.createElement(Inspector$DirectJSON, {
                request: request,
                chain: chain,
                json: variable._0,
                onJsonUpdated: (function (newJson) {
                    return Curry._1(onRequestUpdated, {
                                id: request.id,
                                variableDependencies: Belt_Array.keepMap(request.variableDependencies, (function (variableDependency) {
                                        var dependency = variableDependency.name === variableName ? ({
                                              TAG: 1,
                                              _0: {
                                                name: variableName,
                                                value: {
                                                  TAG: 0,
                                                  _0: newJson,
                                                  [Symbol.for("name")]: "JSON"
                                                }
                                              },
                                              [Symbol.for("name")]: "Direct"
                                            }) : variableDependency.dependency;
                                        return {
                                                name: variableDependency.name,
                                                dependency: dependency
                                              };
                                      })),
                                operation: request.operation,
                                dependencyRequestIds: request.dependencyRequestIds
                              });
                  })
              });
  } else {
    return React.createElement(Inspector$DirectVariable, {
                request: request,
                chain: chain,
                variable: variable._0,
                onVariableUpdated: (function (newVariable) {
                    return Curry._1(onRequestUpdated, {
                                id: request.id,
                                variableDependencies: Belt_Array.keepMap(request.variableDependencies, (function (variableDependency) {
                                        var dependency = variableDependency.name === variableName ? ({
                                              TAG: 1,
                                              _0: {
                                                name: variableName,
                                                value: {
                                                  TAG: 1,
                                                  _0: newVariable,
                                                  [Symbol.for("name")]: "Variable"
                                                }
                                              },
                                              [Symbol.for("name")]: "Direct"
                                            }) : variableDependency.dependency;
                                        return {
                                                name: variableDependency.name,
                                                dependency: dependency
                                              };
                                      })),
                                operation: request.operation,
                                dependencyRequestIds: request.dependencyRequestIds
                              });
                  })
              });
  }
}

var RequestArgument = {
  make: Inspector$RequestArgument
};

var openedArrow = React.createElement("div", {
      className: "rounded-full border border border-indigo w-7 h-7 flex items-center justify-center bg-indigo"
    }, React.createElement("svg", {
          "aria-hidden": true,
          height: "24",
          width: "24",
          fill: "none",
          stroke: "white",
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeWidth: "2",
          viewBox: "0 0 24 24",
          xmlns: "http://www.w3.org/2000/svg"
        }, React.createElement("polyline", {
              points: "18 15 12 9 6 15"
            })));

var closedArrow = React.createElement("div", {
      className: "rounded-full border border-grey w-7 h-7 flex items-center justify-center"
    }, React.createElement("svg", {
          "aria-hidden": true,
          className: "",
          height: "24",
          width: "24",
          fill: "none",
          stroke: "#606F7B",
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeWidth: "2",
          viewBox: "0 0 24 24",
          xmlns: "http://www.w3.org/2000/svg"
        }, React.createElement("polyline", {
              points: "6 9 12 15 18 9"
            })));

function Inspector$Request(Props) {
  var request = Props.request;
  var chain = Props.chain;
  var onChainUpdated = Props.onChainUpdated;
  var schema = Props.schema;
  var onRequestCodeInspected = Props.onRequestCodeInspected;
  var cachedResult = Props.cachedResult;
  var onExecuteRequest = Props.onExecuteRequest;
  var onLogin = Props.onLogin;
  var requestValueCache = Props.requestValueCache;
  var onDeleteEdge = Props.onDeleteEdge;
  var match = React.useState(function () {
        
      });
  var setOpenedTabs = match[1];
  var openedTabs = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setMockedEvalResults = match$1[1];
  var match$2 = React.useState(function () {
        return {};
      });
  var setFormVariables = match$2[1];
  var formVariables = match$2[0];
  React.useEffect((function () {
          var requestsWithLockedVariables = patchChainRequestsArgDeps(chain);
          var chain_name = chain.name;
          var chain_script = chain.script;
          var chain_blocks = chain.blocks;
          var chain$1 = {
            name: chain_name,
            script: chain_script,
            requests: requestsWithLockedVariables,
            blocks: chain_blocks
          };
          var request$1 = patchRequestArgDeps(request);
          var __x = evalRequest(schema, chain$1, request$1, requestValueCache);
          __x.then(function (result) {
                return Promise.resolve(Curry._1(setMockedEvalResults, (function (param) {
                                  if (result.TAG !== /* Ok */0) {
                                    return result;
                                  }
                                  var variables = Js_dict.get(result._0, "variables");
                                  return Belt_Option.map(variables, (function (variables) {
                                                return {
                                                        TAG: 0,
                                                        _0: variables,
                                                        [Symbol.for("name")]: "Ok"
                                                      };
                                              }));
                                })));
              });
          
        }), [
        Belt_Option.getExn(JSON.stringify(request)),
        chain.script
      ]);
  var parsedOperation = Graphql.parse(request.operation.body);
  var definition = Belt_Array.getExn(parsedOperation.definitions, 0);
  var variableNames = Card.getFirstVariables(request.operation);
  var variables = Belt_Array.map(variableNames, (function (param) {
          var variableName = param[0];
          var varDep = Belt_Option.getWithDefault(Belt_Array.getBy(request.variableDependencies, (function (varDep) {
                      return varDep.name === variableName;
                    })), {
                name: variableName,
                dependency: {
                  TAG: 1,
                  _0: {
                    name: variableName,
                    value: {
                      TAG: 0,
                      _0: JSON.parse("\"\""),
                      [Symbol.for("name")]: "JSON"
                    }
                  },
                  [Symbol.for("name")]: "Direct"
                }
              });
          var isOpen = Belt_SetString.has(openedTabs, varDep.name);
          var match = varDep.dependency;
          var tmp;
          tmp = match.TAG === /* ArgumentDependency */0 ? "argument" : (
              match._0.value.TAG === /* JSON */0 ? "json" : "variable"
            );
          return React.createElement("article", {
                      key: variableName,
                      className: "m-2"
                    }, React.createElement("div", {
                          className: "flex justify-between items-center cursor-pointer p-1 bg-gray-600 text-gray-200 border border-green-800 shadow-xl " + (
                            isOpen ? "rounded-t-sm" : "rounded-sm"
                          ),
                          onClick: (function (param) {
                              return Curry._1(setOpenedTabs, (function (oldOpenedTabs) {
                                            if (isOpen) {
                                              return Belt_SetString.remove(oldOpenedTabs, varDep.name);
                                            } else {
                                              return Belt_SetString.add(oldOpenedTabs, varDep.name);
                                            }
                                          }));
                            })
                        }, React.createElement("span", {
                              className: "text-green-500 font-semibold text-sm font-mono"
                            }, "\$" + varDep.name), React.createElement("select", {
                              className: "block text-gray-500 w-min px-3 border border-gray-300 bg-white border-l-0 rounded-md shadow-sm focus:outline-none focus:ring-blue-300 focus:border-blue-300 sm:text-sm rounded-l-none m-0 pt-0 pb-0 pl-4 pr-8",
                              value: tmp,
                              onChange: (function ($$event) {
                                  var match = $$event.target.value;
                                  var newDependency;
                                  switch (match) {
                                    case "argument" :
                                        newDependency = {
                                          TAG: 0,
                                          _0: {
                                            functionFromScript: "INITIAL_UNKNOWN",
                                            maxRecur: undefined,
                                            ifMissing: "SKIP",
                                            ifList: "FIRST",
                                            fromRequestIds: [],
                                            name: varDep.name
                                          },
                                          [Symbol.for("name")]: "ArgumentDependency"
                                        };
                                        break;
                                    case "json" :
                                        newDependency = {
                                          TAG: 1,
                                          _0: {
                                            name: varDep.name,
                                            value: {
                                              TAG: 0,
                                              _0: JSON.parse("{}"),
                                              [Symbol.for("name")]: "JSON"
                                            }
                                          },
                                          [Symbol.for("name")]: "Direct"
                                        };
                                        break;
                                    case "variable" :
                                        newDependency = {
                                          TAG: 1,
                                          _0: {
                                            name: varDep.name,
                                            value: {
                                              TAG: 1,
                                              _0: varDep.name,
                                              [Symbol.for("name")]: "Variable"
                                            }
                                          },
                                          [Symbol.for("name")]: "Direct"
                                        };
                                        break;
                                    default:
                                      newDependency = undefined;
                                  }
                                  if (newDependency === undefined) {
                                    return ;
                                  }
                                  var newVarDep_name = varDep.name;
                                  var newVarDep = {
                                    name: newVarDep_name,
                                    dependency: newDependency
                                  };
                                  var requestHasExistingVariableDependency = Belt_Array.some(request.variableDependencies, (function (existingVarDep) {
                                          return Caml_obj.caml_equal(existingVarDep, varDep);
                                        }));
                                  var newVariableDependencies = requestHasExistingVariableDependency ? Belt_Array.map(request.variableDependencies, (function (existingVarDep) {
                                            if (Caml_obj.caml_equal(existingVarDep, varDep)) {
                                              return newVarDep;
                                            } else {
                                              return existingVarDep;
                                            }
                                          })) : Belt_Array.concat(request.variableDependencies, [newVarDep]);
                                  var newRequest_id = request.id;
                                  var newRequest_operation = request.operation;
                                  var newRequest_dependencyRequestIds = request.dependencyRequestIds;
                                  var newRequest = {
                                    id: newRequest_id,
                                    variableDependencies: newVariableDependencies,
                                    operation: newRequest_operation,
                                    dependencyRequestIds: newRequest_dependencyRequestIds
                                  };
                                  var requests = Belt_Array.map(chain.requests, (function (req) {
                                          if (Caml_obj.caml_equal(req, request)) {
                                            return newRequest;
                                          } else {
                                            return req;
                                          }
                                        }));
                                  var newChain_name = chain.name;
                                  var newChain_script = chain.script;
                                  var newChain_blocks = chain.blocks;
                                  var newChain = {
                                    name: newChain_name,
                                    script: newChain_script,
                                    requests: requests,
                                    blocks: newChain_blocks
                                  };
                                  Curry._1(onChainUpdated, newChain);
                                  return Curry._1(setOpenedTabs, (function (oldOpenedTabs) {
                                                return Belt_SetString.add(oldOpenedTabs, varDep.name);
                                              }));
                                })
                            }, React.createElement("option", {
                                  value: "variable"
                                }, "Variable Input"), React.createElement("option", {
                                  value: "argument"
                                }, "Computed Value"))), React.createElement("div", {
                          className: "text-grey-darkest p-2 bg-gray-600 text-gray-200 overflow-scroll rounded-b-sm " + (
                            isOpen ? "" : "hidden"
                          )
                        }, React.createElement(Inspector$RequestArgument, {
                              request: request,
                              chain: chain,
                              variableName: varDep.name,
                              onRequestUpdated: (function (newRequest) {
                                  return Curry._1(onChainUpdated, {
                                              name: chain.name,
                                              script: chain.script,
                                              requests: Belt_Array.keepMap(chain.requests, (function (existingRequest) {
                                                      return Caml_obj.caml_equal(existingRequest, request) ? newRequest : existingRequest;
                                                    })),
                                              blocks: chain.blocks
                                            });
                                }),
                              defaultRequestArgument: varDep
                            })));
        }));
  var upstreamRequests = Belt_Array.keepMap(request.dependencyRequestIds, (function (upstreamRequestId) {
          var upstreamRequest = Belt_Array.getBy(chain.requests, (function (existingRequest) {
                  return existingRequest.id === upstreamRequestId;
                }));
          return Belt_Option.map(upstreamRequest, (function (upstreamRequest) {
                        return React.createElement("article", {
                                    key: request.id,
                                    className: "m-2"
                                  }, React.createElement("div", {
                                        className: "flex justify-between items-center cursor-pointer p-1 bg-gray-600 text-gray-200 border border-green-800 shadow-xl rounded-sm"
                                      }, React.createElement("span", {
                                            className: "text-green-500 font-semibold text-sm font-mono"
                                          }, upstreamRequest.id), React.createElement("button", {
                                            className: "border-2 border-green-800 p-2 hover:bg-red-900",
                                            onClick: (function ($$event) {
                                                $$event.stopPropagation();
                                                $$event.preventDefault();
                                                return Curry._2(onDeleteEdge, request.id, upstreamRequestId);
                                              })
                                          }, "Remove Dependency")));
                      }));
        }));
  var editor = React.useRef(undefined);
  var compiledDoc = Chain.compileOperationDoc(chain);
  var content = compiledDoc.operationDoc;
  React.useEffect((function () {
          Belt_Option.forEach(editor.current, (function (editor) {
                  editor.setValue(content);
                  
                }));
          
        }), [content]);
  var inputs = Belt_Array.map(Card.getFirstVariables(request.operation), (function (param) {
          var def_variable = {
            name: {
              kind: "Name",
              value: param[0],
              loc: undefined
            }
          };
          var def_type = Graphql.parseType(param[1]);
          var def = {
            variable: def_variable,
            type: def_type
          };
          return formInput(schema, def, setFormVariables, {
                      labelClassname: "underline pl-2 m-2 mt-0 mb-0"
                    });
        }));
  var missingAuthServices = Belt_Option.mapWithDefault(cachedResult, [], (function (results) {
          return OnegraphAuth.findMissingAuthServices(Caml_option.some(results));
        }));
  var authButtons = Belt_Array.map(missingAuthServices, (function (service) {
          return React.createElement("button", {
                      key: service,
                      className: "w-full focus:outline-none text-white text-sm py-2.5 px-5 border-b-4 border-gray-600 rounded-md bg-gray-500 hover:bg-gray-400 m-2",
                      onClick: (function (param) {
                          return Curry._1(onLogin, service);
                        })
                    }, "Log into " + service);
        }));
  return React.createElement("div", {
              className: "max-h-full overflow-y-scroll bg-gray-900"
            }, variables.length !== 0 ? React.createElement(React.Fragment, undefined, React.createElement(Comps.Header.make, {
                        children: "Variable Settings"
                      }), variables) : null, variables.length !== 0 ? React.createElement("div", undefined, React.createElement(Comps.Header.make, {
                        onClick: (function (param) {
                            return Curry._1(onRequestCodeInspected, request);
                          }),
                        children: null
                      }, "Computed Variable Preview", React.createElement(Icons.Export.make, {
                            className: "inline-block ml-2"
                          })), React.createElement("pre", {
                        className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200 overflow-scroll",
                        style: {
                          maxHeight: "150px"
                        }
                      }, Belt_Option.getWithDefault(Belt_Option.map(match$1[0], (function (r) {
                                  var tmp;
                                  tmp = r._0;
                                  return JSON.stringify(tmp, null, 2);
                                })), "Nothing"))) : null, request.dependencyRequestIds.length !== 0 ? React.createElement(React.Fragment, undefined, React.createElement(Comps.Header.make, {
                        children: "Upstream Requests"
                      }), upstreamRequests) : null, React.createElement(Comps.Header.make, {
                  children: "GraphQL Structure"
                }), React.createElement("div", {
                  className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200"
                }, React.createElement(make, {
                      requestId: request.id,
                      schema: schema,
                      definition: definition,
                      onCopy: (function (path) {
                          var dataPath = path.join("?.");
                          var fullPath = "payload." + dataPath;
                          CopyToClipboard(fullPath);
                          
                        })
                    })), React.createElement("div", undefined, React.createElement(Comps.Header.make, {
                      onClick: (function (param) {
                          return Curry._2(onExecuteRequest, request, formVariables);
                        }),
                      children: null
                    }, "Execute block", React.createElement(Icons.Play.make, {
                          className: "inline-block ml-2"
                        })), inputs, authButtons, React.createElement("pre", {
                      className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200"
                    }, Belt_Option.mapWithDefault(cachedResult, "Nothing", (function (json) {
                            return JSON.stringify(json, null, 2);
                          })))));
}

var $$Request = {
  make: Inspector$Request
};

function Inspector$ChainResultsViewer(Props) {
  var chainExecutionResults = Props.chainExecutionResults;
  var content = Belt_Option.getWithDefault(Belt_Option.map(chainExecutionResults, (function (json) {
              return JSON.stringify(json, null, 2);
            })), "");
  var compiledChainViewerEditor = React.useRef(undefined);
  React.useEffect((function () {
          Belt_Option.forEach(compiledChainViewerEditor.current, (function (editor) {
                  editor.setValue(content);
                  
                }));
          
        }), [content]);
  return React.createElement(BsReactMonaco.Editor.make, {
              height: "20%",
              className: "h-auto",
              defaultValue: content,
              language: "graphql",
              theme: "vs-dark",
              options: {
                minimap: {
                  enabled: false
                }
              },
              onMount: (function (editorHandle, _monaco) {
                  compiledChainViewerEditor.current = Caml_option.some(editorHandle);
                  var options = {
                    readOnly: true
                  };
                  editorHandle.updateOptions(options);
                  
                })
            });
}

var ChainResultsViewer = {
  make: Inspector$ChainResultsViewer
};

function Inspector$Nothing(Props) {
  var chain = Props.chain;
  var schema = Props.schema;
  var chainExecutionResults = Props.chainExecutionResults;
  var onLogin = Props.onLogin;
  var onPersistChain = Props.onPersistChain;
  var transformAndExecuteChain = Props.transformAndExecuteChain;
  var onDeleteRequest = Props.onDeleteRequest;
  var onRequestInspected = Props.onRequestInspected;
  var savedChainId = Props.savedChainId;
  var oneGraphAuth = Props.oneGraphAuth;
  var compiledOperation = Chain.compileOperationDoc(chain);
  var missingAuthServices = Belt_Option.getWithDefault(Belt_Option.map(chainExecutionResults, findMissingAuthServicesFromChainResult), []);
  var authButtons = Belt_Array.map(missingAuthServices, (function (service) {
          return React.createElement("button", {
                      key: service,
                      onClick: (function (param) {
                          return Curry._1(onLogin, service);
                        })
                    }, "Log into " + service);
        }));
  var targetChain = Belt_Array.get(compiledOperation.chains, 0);
  var match = React.useState(function () {
        return {};
      });
  var setFormVariables = match[1];
  var formVariables = match[0];
  var form = Belt_Option.getWithDefault(Belt_Option.map(targetChain, (function (targetChain) {
              return Belt_Array.map(targetChain.exposedVariables, (function (exposedVariable) {
                            var def_variable = {
                              name: {
                                kind: "Name",
                                value: exposedVariable.exposedName,
                                loc: undefined
                              }
                            };
                            var def_type = Graphql.parseType(exposedVariable.upstreamType);
                            var def = {
                              variable: def_variable,
                              type: def_type
                            };
                            return formInput(schema, def, setFormVariables, {
                                        labelClassname: "background-blue-400"
                                      });
                          }));
            })), null);
  var isChainViable = chain.requests.length !== 0;
  var requests = Belt_Array.map(chain.requests, (function (request) {
          return React.createElement("article", {
                      key: request.id,
                      className: "m-2"
                    }, React.createElement("div", {
                          className: "flex justify-between items-center cursor-pointer p-1 bg-gray-600 text-gray-200 border border-green-800 shadow-xl rounded-sm"
                        }, React.createElement("span", {
                              className: "text-green-500 font-semibold text-sm font-mono",
                              onClick: (function (param) {
                                  return Curry._1(onRequestInspected, request);
                                })
                            }, request.id), React.createElement("button", {
                              className: "border-2 border-green-800 p-2 hover:bg-red-900",
                              onClick: (function ($$event) {
                                  $$event.stopPropagation();
                                  $$event.preventDefault();
                                  var confirmation = confirm("Really delete \"" + request.operation.title + "\"?");
                                  if (confirmation) {
                                    return Curry._1(onDeleteRequest, request);
                                  }
                                  
                                })
                            }, "Delete")));
        }));
  return React.createElement(React.Fragment, undefined, form, authButtons, isChainViable ? React.createElement(React.Fragment, undefined, React.createElement("button", {
                        className: "w-full focus:outline-none text-white text-sm py-2.5 px-5 border-b-4 border-gray-600 rounded-md bg-gray-500 hover:bg-gray-400 m-2",
                        type: "button",
                        onClick: (function (param) {
                            return Curry._1(transformAndExecuteChain, Caml_option.some(formVariables));
                          })
                      }, "Run chain"), Belt_Option.getWithDefault(Belt_Option.map(chainExecutionResults, (function (chainExecutionResults) {
                              return React.createElement(Inspector$ChainResultsViewer, {
                                          chain: chain,
                                          chainExecutionResults: Caml_option.some(chainExecutionResults)
                                        });
                            })), null), React.createElement("button", {
                        className: "w-full focus:outline-none text-white text-sm py-2.5 px-5 border-b-4 border-gray-600 rounded-md bg-gray-500 hover:bg-gray-400 m-2",
                        type: "button",
                        onClick: (function (param) {
                            return Curry._1(onPersistChain, undefined);
                          })
                      }, "Save Chain")) : "Add some blocks to get started", Belt_Option.getWithDefault(Belt_Option.map(savedChainId, (function (chainId) {
                        return React.createElement("select", {
                                    className: "w-full focus:outline-none text-white text-sm py-2.5 px-5 border-b-4 border-gray-600 rounded-md bg-gray-500 hover:bg-gray-400 m-2",
                                    value: "",
                                    onChange: (function ($$event) {
                                        var chain = Chain.loadFromLocalStorage(chainId);
                                        var appId = oneGraphAuth.appId;
                                        var remoteChainCalls$1 = remoteChainCalls(appId, chainId, Belt_Option.getExn(chain));
                                        var match = $$event.target.value;
                                        var value;
                                        switch (match) {
                                          case "curl" :
                                              value = remoteChainCalls$1.curl;
                                              break;
                                          case "fetch" :
                                              value = remoteChainCalls$1.fetch;
                                              break;
                                          case "form" :
                                              value = "http://localhost:3003/form?form_id=" + chainId;
                                              break;
                                          case "scriptkit" :
                                              value = remoteChainCalls$1.scriptKit;
                                              break;
                                          default:
                                            value = undefined;
                                        }
                                        return Belt_Option.forEach(value, (function (prim) {
                                                      CopyToClipboard(prim);
                                                      
                                                    }));
                                      })
                                  }, React.createElement("option", {
                                        value: ""
                                      }, "> Copy usage"), React.createElement("option", {
                                        value: "form"
                                      }, "Copy link to form"), React.createElement("option", {
                                        value: "fetch"
                                      }, "Copy fetch call"), React.createElement("option", {
                                        value: "curl"
                                      }, "Copy cURL call"), React.createElement("option", {
                                        value: "scriptkit"
                                      }, "Copy ScriptKit usage"));
                      })), null), requests.length !== 0 ? React.createElement(React.Fragment, undefined, React.createElement(Comps.Header.make, {
                        children: "Chain Requests"
                      }), requests) : null, React.createElement(Comps.Header.make, {
                  children: "Internal Debug info"
                }), React.createElement("pre", {
                  className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200 overflow-scroll select-all"
                }, JSON.stringify(chain, null, 2)), React.createElement(Comps.Header.make, {
                  children: "Compiled Executable Chain"
                }), React.createElement("pre", {
                  className: "m-2 p-2 bg-gray-600 rounded-sm text-gray-200 overflow-scroll select-all"
                }, JSON.stringify(Chain.compileOperationDoc(internallyPatchChain(chain)), null, 2)));
}

var Nothing = {
  make: Inspector$Nothing
};

function Inspector(Props) {
  var inspected = Props.inspected;
  var onAddBlock = Props.onAddBlock;
  var onChainUpdated = Props.onChainUpdated;
  var onReset = Props.onReset;
  var chain = Props.chain;
  var schema = Props.schema;
  var chainExecutionResults = Props.chainExecutionResults;
  var onLogin = Props.onLogin;
  var transformAndExecuteChain = Props.transformAndExecuteChain;
  var onPersistChain = Props.onPersistChain;
  var savedChainId = Props.savedChainId;
  var onRequestCodeInspected = Props.onRequestCodeInspected;
  var onExecuteRequest = Props.onExecuteRequest;
  var requestValueCache = Props.requestValueCache;
  var onDeleteRequest = Props.onDeleteRequest;
  var onDeleteEdge = Props.onDeleteEdge;
  var onRequestInspected = Props.onRequestInspected;
  var oneGraphAuth = Props.oneGraphAuth;
  var tmp;
  switch (inspected.TAG | 0) {
    case /* Nothing */0 :
        tmp = "Inspector";
        break;
    case /* Block */1 :
        tmp = "Block." + inspected._0.title;
        break;
    case /* Request */2 :
        tmp = inspected.request.id;
        break;
    case /* RequestArgument */3 :
        tmp = "Request Argument";
        break;
    
  }
  var tmp$1;
  tmp$1 = inspected.TAG === /* Nothing */0 ? null : React.createElement("span", {
          className: "text-white",
          onClick: (function (param) {
              return Curry._1(onReset, undefined);
            })
        }, "X");
  var tmp$2;
  var exit = 0;
  switch (inspected.TAG | 0) {
    case /* Nothing */0 :
        tmp$2 = React.createElement(Inspector$Nothing, {
              chain: inspected._0,
              schema: schema,
              chainExecutionResults: chainExecutionResults,
              onLogin: onLogin,
              onPersistChain: onPersistChain,
              transformAndExecuteChain: transformAndExecuteChain,
              onDeleteRequest: onDeleteRequest,
              onRequestInspected: onRequestInspected,
              savedChainId: savedChainId,
              oneGraphAuth: oneGraphAuth
            });
        break;
    case /* Block */1 :
        tmp$2 = React.createElement(Inspector$Block, {
              schema: schema,
              block: inspected._0,
              onAddBlock: onAddBlock
            });
        break;
    case /* Request */2 :
    case /* RequestArgument */3 :
        exit = 1;
        break;
    
  }
  if (exit === 1) {
    var request = inspected.request;
    var cachedResult = Js_dict.get(requestValueCache, request.id);
    tmp$2 = React.createElement(Inspector$Request, {
          request: request,
          chain: chain,
          onChainUpdated: onChainUpdated,
          inspected: inspected,
          schema: schema,
          onRequestCodeInspected: onRequestCodeInspected,
          cachedResult: cachedResult,
          onExecuteRequest: onExecuteRequest,
          onLogin: onLogin,
          requestValueCache: requestValueCache,
          onDeleteEdge: onDeleteEdge
        });
  }
  return React.createElement("div", {
              className: "h-screen text-white border-l border-gray-800 bg-gray-900"
            }, React.createElement("div", undefined, React.createElement("nav", {
                      className: "flex flex-row py-1 px-2 mb-2"
                    }, React.createElement("button", {
                          className: "text-left text-gray-600 hover:text-blue-500 focus:outline-none text-blue-500 flex-grow"
                        }, tmp), tmp$1)), tmp$2);
}

var special_token = "XlMpa0MEz1ZMIYtebUGttQpV9I8CCwL5VejNbfStd2c";

var activeTabClasses = "text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none text-blue-500 border-b-2 font-medium border-blue-500";

var inactiveTabClass = "text-white py-4 px-6 block hover:text-blue-500 focus:outline-none";

var make$1 = Inspector;

export {
  special_token ,
  AdvancedMode ,
  Clipboard ,
  GraphQLPreview ,
  formInput ,
  transpileFullChainScript ,
  patchRequestArgDeps ,
  patchChainRequestsArgDeps ,
  evalRequest ,
  findMissingAuthServicesFromChainResult ,
  internallyPatchChain ,
  transformChain ,
  remoteChainCalls ,
  transformAndExecuteChain ,
  Block ,
  DirectVariable ,
  DirectJSON ,
  ArgumentDependency ,
  emptyArgumentDependency ,
  RequestArgument ,
  openedArrow ,
  closedArrow ,
  $$Request ,
  ChainResultsViewer ,
  Nothing ,
  activeTabClasses ,
  inactiveTabClass ,
  make$1 as make,
  
}
/* make Not a pure module */
