// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Comps from "./Comps.mjs";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";
import * as Hooks from "react-relay/hooks";
import * as RescriptRelay_Internal from "rescript-relay/src/RescriptRelay_Internal.mjs";
import * as PackageInfo_npmPackage_graphql from "../__generated__/PackageInfo_npmPackage_graphql.mjs";

function use(fRef) {
  var data = Hooks.useFragment(PackageInfo_npmPackage_graphql.node, fRef);
  return RescriptRelay_Internal.internal_useConvertedValue(PackageInfo_npmPackage_graphql.Internal.convertFragment, data);
}

function useOpt(opt_fRef) {
  var fr = opt_fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(opt_fRef)) : undefined;
  var nullableFragmentData = Hooks.useFragment(PackageInfo_npmPackage_graphql.node, fr !== undefined ? Js_null_undefined.fromOption(Caml_option.some(Caml_option.valFromOption(fr))) : null);
  var data = (nullableFragmentData == null) ? undefined : Caml_option.some(nullableFragmentData);
  return RescriptRelay_Internal.internal_useConvertedValue((function (rawFragment) {
                if (rawFragment !== undefined) {
                  return PackageInfo_npmPackage_graphql.Internal.convertFragment(rawFragment);
                }
                
              }), data);
}

var NpmPackageFragment = {
  Types: undefined,
  use: use,
  useOpt: useOpt
};

function PackageInfo(Props) {
  var npmPackage = Props.npmPackage;
  var npmPackage$1 = use(npmPackage);
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, Belt_Option.getWithDefault(npmPackage$1.name, "<No name>")), React.createElement("p", undefined, Belt_Option.getWithDefault(npmPackage$1.description, "")), React.createElement(Comps.Pre.make, {
                  children: JSON.stringify(npmPackage$1, null, 2)
                }));
}

var make = PackageInfo;

export {
  NpmPackageFragment ,
  make ,
  
}
/* Comps Not a pure module */
