// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RequestValueCache from "../RequestValueCache.mjs";

var empty = RequestValueCache.make(undefined);

var context = React.createContext(empty);

var provider = context.Provider;

function RequestValueCacheProvider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var make = RequestValueCacheProvider;

export {
  empty ,
  context ,
  provider ,
  make ,
  
}
/* empty Not a pure module */
