// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.mjs";

function Icons$Play(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zM9 18V6l10 6-10 6z",
                  fill: color
                }));
}

var Play = {
  make: Icons$Play
};

function Icons$Inspect(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    enableBackground: "new 0 0 330 330",
    version: "1.1",
    viewBox: "0 0 330 330",
    x: "0",
    xmlns: "http://www.w3.org/2000/svg",
    xmlSpace: "preserve",
    y: "0"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M325.606 304.393l-42.276-42.275c10.49-14.716 16.666-32.71 16.666-52.118 0-26.593-11.598-50.526-29.996-67.017V75.001c0-8.284-6.716-15-15-15h-45v-45c0-8.284-6.716-15-15-15H75c-8.284 0-15 6.716-15 15v45H15c-8.284 0-15 6.716-15 15V235c0 8.284 6.716 15 15 15h114.391c14.752 29.608 45.34 50 80.605 50 19.41 0 37.404-6.177 52.122-16.668l42.275 42.275C307.322 328.535 311.161 330 315 330s7.678-1.464 10.606-4.393c5.859-5.859 5.859-15.356 0-21.214zM90 30.001h90v30H90v-30zM30 220V90.001h210v35.148A89.593 89.593 0 00209.996 120c-49.626 0-90 40.374-90 90 0 3.38.193 6.715.559 10H30zm119.996-10c0-33.084 26.916-60 60-60s60 26.916 60 60-26.916 60-60 60-60-26.916-60-60z",
                  fill: color
                }));
}

var Inspect = {
  make: Icons$Inspect
};

function Icons$GraphQL(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    "aria-hidden": true,
    height: height,
    width: width,
    transform: "rotate(360)",
    viewBox: "0 0 256 288",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M152.576 32.963l59.146 34.15a25.819 25.819 0 015.818-4.604c12.266-7.052 27.912-2.865 35.037 9.402 7.052 12.267 2.865 27.912-9.402 35.037a25.698 25.698 0 01-6.831 2.72v68.325a25.7 25.7 0 016.758 2.702c12.34 7.125 16.527 22.771 9.402 35.038-7.052 12.266-22.771 16.453-35.038 9.402a25.464 25.464 0 01-6.34-5.147l-58.786 33.94a25.671 25.671 0 011.295 8.08c0 14.103-11.458 25.636-25.635 25.636-14.177 0-25.635-11.46-25.635-25.636 0-2.52.362-4.954 1.037-7.253l-59.13-34.14a25.824 25.824 0 01-5.738 4.52c-12.34 7.051-27.986 2.864-35.038-9.402-7.051-12.267-2.864-27.913 9.402-35.038a25.71 25.71 0 016.758-2.703v-68.324a25.698 25.698 0 01-6.831-2.72C.558 99.897-3.629 84.178 3.423 71.911c7.052-12.267 22.77-16.454 35.037-9.402a25.82 25.82 0 015.79 4.575l59.163-34.159a25.707 25.707 0 01-1.048-7.29C102.365 11.46 113.823 0 128 0c14.177 0 25.635 11.459 25.635 25.635 0 2.548-.37 5.007-1.059 7.328zm-6.162 10.522l59.287 34.23a25.599 25.599 0 002.437 19.831c3.609 6.278 9.488 10.44 16.013 12.062v68.41c-.333.081-.664.17-.993.264L145.725 44.17c.234-.224.464-.452.689-.684zm-36.123.7l-77.432 134.11a25.824 25.824 0 00-1.01-.27v-68.417c6.525-1.622 12.404-5.784 16.013-12.062a25.6 25.6 0 002.427-19.869l59.27-34.22c.239.247.483.49.732.727zm24.872 6.075l77.414 134.08a25.492 25.492 0 00-4.513 5.757 25.7 25.7 0 00-2.702 6.758H50.64a25.71 25.71 0 00-2.704-6.758 25.825 25.825 0 00-4.506-5.724l77.429-134.107A25.715 25.715 0 00128 51.27c2.487 0 4.89-.352 7.163-1.01zm11.795 194.478l58.902-34.008a25.865 25.865 0 01-.473-1.682H50.607a25.87 25.87 0 01-.266.992l59.19 34.175A25.558 25.558 0 01128 236.373a25.564 25.564 0 0118.958 8.365z",
                  fill: color,
                  fillRule: "evenodd"
                }));
}

var GraphQL = {
  make: Icons$GraphQL
};

function Icons$PureScript(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M19.166 4.6l-1.24 1.24 3.97 3.97-3.97 3.97 1.24 1.24 4.58-4.6a.87.87 0 000-1.23zM6.955 6.74l1.87 1.75h8.23l-1.87-1.75zm-2.1 2.24l-4.6 4.6a.87.87 0 000 1.23l4.6 4.59 1.23-1.24-3.97-3.97 3.97-3.97-1.24-1.24zm3.97 2.14l-1.87 1.76h8.23l1.87-1.76zm-1.87 4.39l1.87 1.75h8.23l-1.87-1.75z",
                  fill: color
                }));
}

var PureScript = {
  make: Icons$PureScript
};

function Icons$TypeScript(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var onClick = Props.onClick;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M1.125 0C.502 0 0 .502 0 1.125v21.75C0 23.498.502 24 1.125 24h21.75c.623 0 1.125-.502 1.125-1.125V1.125C24 .502 23.498 0 22.875 0zm17.363 9.75c.612 0 1.154.037 1.627.111a6.38 6.38 0 011.306.34v2.458a3.95 3.95 0 00-.643-.361 5.093 5.093 0 00-.717-.26 5.453 5.453 0 00-1.426-.2c-.3 0-.573.028-.819.086a2.1 2.1 0 00-.623.242c-.17.104-.3.229-.393.374a.888.888 0 00-.14.49c0 .196.053.373.156.529.104.156.252.304.443.444s.423.276.696.41c.273.135.582.274.926.416.47.197.892.407 1.266.628.374.222.695.473.963.753.268.279.472.598.614.957.142.359.214.776.214 1.253 0 .657-.125 1.21-.373 1.656a3.033 3.033 0 01-1.012 1.085 4.38 4.38 0 01-1.487.596c-.566.12-1.163.18-1.79.18a9.916 9.916 0 01-1.84-.164 5.544 5.544 0 01-1.512-.493v-2.63a5.033 5.033 0 003.237 1.2c.333 0 .624-.03.872-.09.249-.06.456-.144.623-.25.166-.108.29-.234.373-.38a1.023 1.023 0 00-.074-1.089 2.12 2.12 0 00-.537-.5 5.597 5.597 0 00-.807-.444 27.72 27.72 0 00-1.007-.436c-.918-.383-1.602-.852-2.053-1.405-.45-.553-.676-1.222-.676-2.005 0-.614.123-1.141.369-1.582.246-.441.58-.804 1.004-1.089a4.494 4.494 0 011.47-.629 7.536 7.536 0 011.77-.201zm-15.113.188h9.563v2.166H9.506v9.646H6.789v-9.646H3.375z",
                  fill: color
                }));
}

var TypeScript = {
  make: Icons$TypeScript
};

function Icons$Export(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 90 112.5",
    x: "0",
    xmlns: "http://www.w3.org/2000/svg",
    y: "0"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M65.261 76.833L13.167 76.833 13.167 24.739 44.511 24.739 53.428 15.823 4.25 15.823 4.25 85.75 74.177 85.75 74.177 36.572 65.261 45.489z",
                  fill: color
                }), React.createElement("path", {
                  d: "M54.385 8.53L63.438 17.582 23.67 57.349 32.651 66.33 60.629 38.351 69.546 29.434 72.418 26.562 81.47 35.615 85.75 4.25z",
                  fill: color
                }));
}

var Export = {
  make: Icons$Export
};

function Icons$Trash(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M6 19C6 20.1 6.9 21 8 21H16C17.1 21 18 20.1 18 19V7H6V19ZM8 9H16V19H8V9ZM15.5 4L14.5 3H9.5L8.5 4H5V6H19V4H15.5Z",
                  fill: color
                }));
}

var Trash = {
  make: Icons$Trash
};

function Icons$Search(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z",
                  fill: color
                }));
}

var Search = {
  make: Icons$Search
};

function Icons$CaretUp(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M13.825 12.8417L10 9.02501L6.175 12.8417L5 11.6667L10 6.66667L15 11.6667L13.825 12.8417Z",
                  fill: color
                }));
}

var CaretUp = {
  make: Icons$CaretUp
};

function Icons$CaretRight(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M7.15832 6.175L10.975 10L7.15833 13.825L8.33333 15L13.3333 10L8.33332 5L7.15832 6.175Z",
                  fill: color
                }));
}

var CaretRight = {
  make: Icons$CaretRight
};

function Icons$Prettier$Dark(Props) {
  var className = Props.className;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 210 210",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", {
                  fill: "none",
                  fillRule: "evenodd",
                  stroke: "none",
                  strokeWidth: "1"
                }, React.createElement("g", undefined, React.createElement("g", undefined, React.createElement("g", {
                              transform: "translate(0 200)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "150",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "70",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 180)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "160",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "130",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "40",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 160)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "100",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "110",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 140)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "140",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "100",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "30",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 120)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "170",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "60",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 100)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "90",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "80",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "30",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 80)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "190",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 60)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "190",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "40",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 40)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "150",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "90",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "80",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 20)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "170",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "110",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "50",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", undefined, React.createElement("rect", {
                                  height: "10",
                                  width: "70",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "140",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "130",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                }))))));
}

var Dark = {
  make: Icons$Prettier$Dark
};

var Prettier = {
  Dark: Dark
};

function Icons$Form(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    enableBackground: "new 0 0 100 100",
    viewBox: "0 0 100 125",
    x: "0px",
    y: "0px"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", undefined, React.createElement("path", {
                      d: "M82.49,94.962H17.51V5.035h64.98V94.962z M19.112,93.359h61.775V6.637H19.112V93.359z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M74.257,32.762H25.743V14.5h48.514V32.762z M27.345,31.159h45.309V16.102H27.345V31.159z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M74.056,51.205H25.943v-9.532h48.112V51.205z M27.146,50.003h45.709v-7.128H27.146V50.003z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M74.056,68.911H25.943V59.38h48.112V68.911z M27.146,67.71h45.709v-7.129H27.146V67.71z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M35.952,86.143h-9.213v-9.214h9.213V86.143z M27.94,84.94h6.811V78.13H27.94V84.94z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M73.968,86.143h-9.213v-9.214h9.213V86.143z M65.956,84.94h6.81V78.13h-6.81V84.94z",
                      fill: color
                    })), React.createElement("g", undefined, React.createElement("path", {
                      d: "M54.96,86.143h-9.213v-9.214h9.213V86.143z M46.948,84.94h6.811V78.13h-6.811V84.94z",
                      fill: color
                    })));
}

var Form = {
  make: Icons$Form
};

function Icons$Gears(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 418.879 418.879"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", undefined, React.createElement("g", undefined, React.createElement("path", {
                          d: "M188.634,234.066c8.462-5.287,16.126-11.735,22.767-19.127l23.942,13.826l21.8-37.76l-23.894-13.796\n\t\t\tc3.038-9.275,4.825-19.113,5.16-29.311l27.183-4.793l-7.574-42.938l-27.178,4.793c-3.756-9.309-8.795-17.965-14.906-25.744\n\t\t\tl17.766-21.17L200.3,30.022l-17.751,21.152c-8.67-4.646-18.059-8.119-27.954-10.203V13.385h-43.6v27.586\n\t\t\tc-9.896,2.084-19.285,5.557-27.956,10.203l-17.75-21.152l-33.4,28.025l17.764,21.17c-6.11,7.779-11.149,16.436-14.905,25.744\n\t\t\tL7.57,100.168L0,143.106l27.179,4.793c0.335,10.199,2.123,20.035,5.161,29.313L8.444,191.007l21.801,37.759l23.943-13.822\n\t\t\tc6.639,7.389,14.303,13.838,22.766,19.125l-9.451,25.963l40.972,14.91l9.438-25.928c4.864,0.688,9.831,1.053,14.882,1.053\n\t\t\tc5.051,0,10.019-0.363,14.883-1.053l9.437,25.93l40.97-14.914L188.634,234.066z M132.793,200.065\n\t\t\tc-30.702,0-55.68-24.977-55.68-55.68c0-30.701,24.978-55.68,55.68-55.68s55.68,24.979,55.68,55.68\n\t\t\tC188.473,175.088,163.496,200.065,132.793,200.065z",
                          fill: color
                        }), React.createElement("path", {
                          d: "M376.041,266.807l-18.795,6.08c-3.584-6.229-8.014-11.869-13.115-16.779l10.504-16.764l-26.447-16.57l-10.498,16.75\n\t\t\tc-6.604-2.438-13.602-3.973-20.826-4.471l-2.725-19.559l-30.912,4.309l2.725,19.559c-6.809,2.453-13.125,5.847-18.812,9.996\n\t\t\tl-14.672-13.244l-20.912,23.168l14.684,13.259c-3.562,6.118-6.277,12.752-8.02,19.726l-19.744-0.714l-1.129,31.188l19.743,0.716\n\t\t\tc1.246,7.198,3.486,13.991,6.558,20.271l-15.578,12.143l19.185,24.615l15.609-12.164c5.438,4.582,11.511,8.396,18.031,11.311\n\t\t\tl-4.138,19.344l30.522,6.52l4.133-19.314c3.516,0.01,7.072-0.229,10.652-0.727c3.582-0.498,7.07-1.25,10.447-2.215l9.256,17.451\n\t\t\tl27.574-14.623l-9.266-17.471c5.48-4.586,10.271-9.918,14.252-15.812l18.338,7.436l11.727-28.924l-18.303-7.422\n\t\t\tc1.234-6.875,1.529-14.027,0.764-21.293l18.799-6.084L376.041,266.807z M297.129,350.006\n\t\t\tc-21.771,3.031-41.949-12.209-44.98-33.977c-3.037-21.769,12.207-41.949,33.977-44.979c21.768-3.036,41.941,12.207,44.98,33.978\n\t\t\tC334.135,326.795,318.896,346.969,297.129,350.006z",
                          fill: color
                        }), React.createElement("path", {
                          d: "M418.146,158.647l0.732-24.629l-15.586-0.463c-0.977-5.428-2.723-10.803-5.285-15.971l12.24-9.67l-15.271-19.33\n\t\t\tl-12.238,9.666c-4.365-3.627-9.193-6.584-14.318-8.816l3.164-15.291l-24.123-4.996l-3.17,15.281\n\t\t\tc-5.559,0.008-11.156,0.797-16.641,2.412l-7.391-13.727l-21.695,11.684l7.391,13.729c-4.363,3.686-8.107,7.934-11.176,12.566\n\t\t\tl-14.496-5.77l-9.111,22.893l14.508,5.779c-0.955,5.508-1.141,11.158-0.514,16.799l-14.809,4.898l7.732,23.395l14.809-4.896\n\t\t\tc2.9,4.986,6.426,9.396,10.426,13.201l-8.191,13.268l20.963,12.946l8.209-13.292c5.285,1.896,10.828,3.051,16.453,3.414\n\t\t\tl2.252,15.453l24.383-3.561l-2.246-15.434c2.602-0.957,5.17-2.109,7.684-3.463c2.516-1.352,4.891-2.867,7.123-4.51l11.648,10.371\n\t\t\tl16.387-18.398l-11.656-10.383c2.795-4.9,4.875-10.164,6.203-15.619L418.146,158.647z M359.436,171.844\n\t\t\tc-15.281,8.227-34.404,2.492-42.627-12.783c-8.23-15.277-2.494-34.404,12.787-42.627c15.273-8.229,34.395-2.49,42.625,12.787\n\t\t\tC380.443,144.499,374.711,163.616,359.436,171.844z",
                          fill: color
                        }))));
}

var Gears = {
  make: Icons$Gears
};

function Icons$Save(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 453.03 453.03"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M388.49,0H0.022v453.03h452.986V64.561L388.49,0z M385.017,221.834H110.68V25.691h274.337V221.834z",
                  fill: color
                }), React.createElement("rect", {
                  height: "154.102",
                  width: "80.718",
                  fill: color,
                  x: "272.568",
                  y: "46.701"
                }));
}

var Save = {
  make: Icons$Save
};

function Icons$Link(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M3.24999 9.99998C3.24999 8.57498 4.40832 7.41665 5.83332 7.41665H9.16666V5.83331H5.83332C3.53332 5.83331 1.66666 7.69998 1.66666 9.99998C1.66666 12.3 3.53332 14.1666 5.83332 14.1666H9.16666V12.5833H5.83332C4.40832 12.5833 3.24999 11.425 3.24999 9.99998ZM6.66666 10.8333H13.3333V9.16665H6.66666V10.8333ZM14.1667 5.83331H10.8333V7.41665H14.1667C15.5917 7.41665 16.75 8.57498 16.75 9.99998C16.75 11.425 15.5917 12.5833 14.1667 12.5833H10.8333V14.1666H14.1667C16.4667 14.1666 18.3333 12.3 18.3333 9.99998C18.3333 7.69998 16.4667 5.83331 14.1667 5.83331Z",
                  fill: color
                }));
}

var Link = {
  make: Icons$Link
};

function Icons$RunLink(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 17 10"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M5 3.33333H11.6667V5H5V3.33333ZM15.0833 4.16667H16.6667C16.6667 1.86667 14.8 0 12.5 0H9.16667V1.58333H12.5C13.925 1.58333 15.0833 2.74167 15.0833 4.16667ZM1.58333 4.16667C1.58333 2.74167 2.74167 1.58333 4.16667 1.58333H7.5V0H4.16667C1.86667 0 0 1.86667 0 4.16667C0 6.46667 1.86667 8.33333 4.16667 8.33333H7.5V6.75H4.16667C2.74167 6.75 1.58333 5.59167 1.58333 4.16667Z",
                  fill: color
                }), React.createElement("path", {
                  d: "M12.5 4.33335V9.16667L16.6667 6.75L12.5 4.33335Z",
                  fill: color
                }), React.createElement("path", {
                  d: "M9.16667 6.75H11.3333V8.33333H9.16667V6.75Z",
                  fill: color
                }), React.createElement("path", {
                  d: "M16.6667 4.16667H15.0833L16.6667 5.34026V4.16667Z",
                  fill: color
                }));
}

var RunLink = {
  make: Icons$RunLink
};

function Icons$List(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M15.8333 4.16667V15.8333H4.16667V4.16667H15.8333ZM16.75 2.5H3.25C2.83333 2.5 2.5 2.83333 2.5 3.25V16.75C2.5 17.0833 2.83333 17.5 3.25 17.5H16.75C17.0833 17.5 17.5 17.0833 17.5 16.75V3.25C17.5 2.83333 17.0833 2.5 16.75 2.5ZM9.16667 5.83333H14.1667V7.5H9.16667V5.83333ZM9.16667 9.16667H14.1667V10.8333H9.16667V9.16667ZM9.16667 12.5H14.1667V14.1667H9.16667V12.5ZM5.83333 5.83333H7.5V7.5H5.83333V5.83333ZM5.83333 9.16667H7.5V10.8333H5.83333V9.16667ZM5.83333 12.5H7.5V14.1667H5.83333V12.5Z",
                  fill: color
                }));
}

var List = {
  make: Icons$List
};

function Icons$OpenInNew(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M15.8333 15.8333H4.16667V4.16667H10V2.5H4.16667C3.24167 2.5 2.5 3.25 2.5 4.16667V15.8333C2.5 16.75 3.24167 17.5 4.16667 17.5H15.8333C16.75 17.5 17.5 16.75 17.5 15.8333V10H15.8333V15.8333ZM11.6667 2.5V4.16667H14.6583L6.46667 12.3583L7.64167 13.5333L15.8333 5.34167V8.33333H17.5V2.5H11.6667Z",
                  fill: color
                }));
}

var OpenInNew = {
  make: Icons$OpenInNew
};

function Icons$AddLink(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M6.66669 9.16665H13.3334V10.8333H6.66669V9.16665ZM16.75 9.99998H18.3334C18.3334 7.69998 16.4667 5.83331 14.1667 5.83331H10.8334V7.41665H14.1667C15.5917 7.41665 16.75 8.57498 16.75 9.99998ZM3.25002 9.99998C3.25002 8.57498 4.40835 7.41665 5.83335 7.41665H9.16669V5.83331H5.83335C3.53335 5.83331 1.66669 7.69998 1.66669 9.99998C1.66669 12.3 3.53335 14.1666 5.83335 14.1666H9.16669V12.5833H5.83335C4.40835 12.5833 3.25002 11.425 3.25002 9.99998ZM15.8334 9.99998H14.1667V12.5H11.6667V14.1666H14.1667V16.6666H15.8334V14.1666H18.3334V12.5H15.8334V9.99998Z",
                  fill: color
                }));
}

var AddLink = {
  make: Icons$AddLink
};

function Icons$Mediation(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M18.3333 10L15 13.3334L13.825 12.1584L15.1416 10.8334H10.7833C10.5 13.4167 8.89996 15.6 6.66663 16.7084C6.63329 18.075 5.53329 19.1667 4.16663 19.1667C2.78329 19.1667 1.66663 18.05 1.66663 16.6667C1.66663 15.2834 2.78329 14.1667 4.16663 14.1667C4.95829 14.1667 5.64996 14.5417 6.10829 15.1167C7.69163 14.2584 8.82496 12.6917 9.09163 10.8334H6.50829C6.16663 11.8 5.24996 12.5 4.16663 12.5C2.78329 12.5 1.66663 11.3834 1.66663 10C1.66663 8.61671 2.78329 7.50004 4.16663 7.50004C5.24996 7.50004 6.16663 8.20004 6.51663 9.16671H9.09996C8.83329 7.30837 7.69163 5.75004 6.10829 4.88337C5.64996 5.45837 4.95829 5.83337 4.16663 5.83337C2.78329 5.83337 1.66663 4.71671 1.66663 3.33337C1.66663 1.95004 2.78329 0.833374 4.16663 0.833374C5.53329 0.833374 6.63329 1.92504 6.65829 3.29171C8.89163 4.40004 10.4916 6.58337 10.775 9.16671H15.1333L13.8166 7.84171L15 6.66671L18.3333 10Z",
                  fill: color
                }));
}

var Mediation = {
  make: Icons$Mediation
};

function Icons$ContentCopy(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M13.3334 0.833374H3.33335C2.41669 0.833374 1.66669 1.58337 1.66669 2.50004V14.1667H3.33335V2.50004H13.3334V0.833374ZM15.8334 4.16671H6.66669C5.75002 4.16671 5.00002 4.91671 5.00002 5.83337V17.5C5.00002 18.4167 5.75002 19.1667 6.66669 19.1667H15.8334C16.75 19.1667 17.5 18.4167 17.5 17.5V5.83337C17.5 4.91671 16.75 4.16671 15.8334 4.16671ZM15.8334 17.5H6.66669V5.83337H15.8334V17.5Z",
                  fill: color
                }));
}

var ContentCopy = {
  make: Icons$ContentCopy
};

function Icons$Login(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    fill: "none",
    viewBox: "0 0 20 20"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M9.16669 5.83333L8.00002 7L10.1667 9.16667H1.66669V10.8333H10.1667L8.00002 13L9.16669 14.1667L13.3334 10L9.16669 5.83333ZM16.6667 15.8333H10V17.5H16.6667C17.5834 17.5 18.3334 16.75 18.3334 15.8333V4.16667C18.3334 3.25 17.5834 2.5 16.6667 2.5H10V4.16667H16.6667V15.8333Z",
                  fill: color
                }));
}

var Login = {
  make: Icons$Login
};

export {
  Play ,
  Inspect ,
  GraphQL ,
  PureScript ,
  TypeScript ,
  Export ,
  Trash ,
  Search ,
  CaretUp ,
  CaretRight ,
  Prettier ,
  Form ,
  Gears ,
  Save ,
  Link ,
  RunLink ,
  List ,
  OpenInNew ,
  AddLink ,
  Mediation ,
  ContentCopy ,
  Login ,
  
}
/* react Not a pure module */
