// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.mjs";

function Icons$Play(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zM9 18V6l10 6-10 6z",
                  fill: color,
                  stroke: color
                }));
}

var Play = {
  make: Icons$Play
};

function Icons$Inspect(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    enableBackground: "new 0 0 330 330",
    version: "1.1",
    viewBox: "0 0 330 330",
    x: "0",
    xmlns: "http://www.w3.org/2000/svg",
    xmlSpace: "preserve",
    y: "0"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M325.606 304.393l-42.276-42.275c10.49-14.716 16.666-32.71 16.666-52.118 0-26.593-11.598-50.526-29.996-67.017V75.001c0-8.284-6.716-15-15-15h-45v-45c0-8.284-6.716-15-15-15H75c-8.284 0-15 6.716-15 15v45H15c-8.284 0-15 6.716-15 15V235c0 8.284 6.716 15 15 15h114.391c14.752 29.608 45.34 50 80.605 50 19.41 0 37.404-6.177 52.122-16.668l42.275 42.275C307.322 328.535 311.161 330 315 330s7.678-1.464 10.606-4.393c5.859-5.859 5.859-15.356 0-21.214zM90 30.001h90v30H90v-30zM30 220V90.001h210v35.148A89.593 89.593 0 00209.996 120c-49.626 0-90 40.374-90 90 0 3.38.193 6.715.559 10H30zm119.996-10c0-33.084 26.916-60 60-60s60 26.916 60 60-26.916 60-60 60-60-26.916-60-60z",
                  fill: color,
                  stroke: color
                }));
}

var Inspect = {
  make: Icons$Inspect
};

function Icons$GraphQL(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    "aria-hidden": true,
    height: height,
    width: width,
    transform: "rotate(360)",
    viewBox: "0 0 256 288",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M152.576 32.963l59.146 34.15a25.819 25.819 0 015.818-4.604c12.266-7.052 27.912-2.865 35.037 9.402 7.052 12.267 2.865 27.912-9.402 35.037a25.698 25.698 0 01-6.831 2.72v68.325a25.7 25.7 0 016.758 2.702c12.34 7.125 16.527 22.771 9.402 35.038-7.052 12.266-22.771 16.453-35.038 9.402a25.464 25.464 0 01-6.34-5.147l-58.786 33.94a25.671 25.671 0 011.295 8.08c0 14.103-11.458 25.636-25.635 25.636-14.177 0-25.635-11.46-25.635-25.636 0-2.52.362-4.954 1.037-7.253l-59.13-34.14a25.824 25.824 0 01-5.738 4.52c-12.34 7.051-27.986 2.864-35.038-9.402-7.051-12.267-2.864-27.913 9.402-35.038a25.71 25.71 0 016.758-2.703v-68.324a25.698 25.698 0 01-6.831-2.72C.558 99.897-3.629 84.178 3.423 71.911c7.052-12.267 22.77-16.454 35.037-9.402a25.82 25.82 0 015.79 4.575l59.163-34.159a25.707 25.707 0 01-1.048-7.29C102.365 11.46 113.823 0 128 0c14.177 0 25.635 11.459 25.635 25.635 0 2.548-.37 5.007-1.059 7.328zm-6.162 10.522l59.287 34.23a25.599 25.599 0 002.437 19.831c3.609 6.278 9.488 10.44 16.013 12.062v68.41c-.333.081-.664.17-.993.264L145.725 44.17c.234-.224.464-.452.689-.684zm-36.123.7l-77.432 134.11a25.824 25.824 0 00-1.01-.27v-68.417c6.525-1.622 12.404-5.784 16.013-12.062a25.6 25.6 0 002.427-19.869l59.27-34.22c.239.247.483.49.732.727zm24.872 6.075l77.414 134.08a25.492 25.492 0 00-4.513 5.757 25.7 25.7 0 00-2.702 6.758H50.64a25.71 25.71 0 00-2.704-6.758 25.825 25.825 0 00-4.506-5.724l77.429-134.107A25.715 25.715 0 00128 51.27c2.487 0 4.89-.352 7.163-1.01zm11.795 194.478l58.902-34.008a25.865 25.865 0 01-.473-1.682H50.607a25.87 25.87 0 01-.266.992l59.19 34.175A25.558 25.558 0 01128 236.373a25.564 25.564 0 0118.958 8.365z",
                  fill: color,
                  fillRule: "evenodd",
                  stroke: color
                }));
}

var GraphQL = {
  make: Icons$GraphQL
};

function Icons$PureScript(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M19.166 4.6l-1.24 1.24 3.97 3.97-3.97 3.97 1.24 1.24 4.58-4.6a.87.87 0 000-1.23zM6.955 6.74l1.87 1.75h8.23l-1.87-1.75zm-2.1 2.24l-4.6 4.6a.87.87 0 000 1.23l4.6 4.59 1.23-1.24-3.97-3.97 3.97-3.97-1.24-1.24zm3.97 2.14l-1.87 1.76h8.23l1.87-1.76zm-1.87 4.39l1.87 1.75h8.23l-1.87-1.75z",
                  fill: color,
                  stroke: color
                }));
}

var PureScript = {
  make: Icons$PureScript
};

function Icons$TypeScript(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var onClick = Props.onClick;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M1.125 0C.502 0 0 .502 0 1.125v21.75C0 23.498.502 24 1.125 24h21.75c.623 0 1.125-.502 1.125-1.125V1.125C24 .502 23.498 0 22.875 0zm17.363 9.75c.612 0 1.154.037 1.627.111a6.38 6.38 0 011.306.34v2.458a3.95 3.95 0 00-.643-.361 5.093 5.093 0 00-.717-.26 5.453 5.453 0 00-1.426-.2c-.3 0-.573.028-.819.086a2.1 2.1 0 00-.623.242c-.17.104-.3.229-.393.374a.888.888 0 00-.14.49c0 .196.053.373.156.529.104.156.252.304.443.444s.423.276.696.41c.273.135.582.274.926.416.47.197.892.407 1.266.628.374.222.695.473.963.753.268.279.472.598.614.957.142.359.214.776.214 1.253 0 .657-.125 1.21-.373 1.656a3.033 3.033 0 01-1.012 1.085 4.38 4.38 0 01-1.487.596c-.566.12-1.163.18-1.79.18a9.916 9.916 0 01-1.84-.164 5.544 5.544 0 01-1.512-.493v-2.63a5.033 5.033 0 003.237 1.2c.333 0 .624-.03.872-.09.249-.06.456-.144.623-.25.166-.108.29-.234.373-.38a1.023 1.023 0 00-.074-1.089 2.12 2.12 0 00-.537-.5 5.597 5.597 0 00-.807-.444 27.72 27.72 0 00-1.007-.436c-.918-.383-1.602-.852-2.053-1.405-.45-.553-.676-1.222-.676-2.005 0-.614.123-1.141.369-1.582.246-.441.58-.804 1.004-1.089a4.494 4.494 0 011.47-.629 7.536 7.536 0 011.77-.201zm-15.113.188h9.563v2.166H9.506v9.646H6.789v-9.646H3.375z",
                  fill: color,
                  stroke: color
                }));
}

var TypeScript = {
  make: Icons$TypeScript
};

function Icons$Export(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 90 112.5",
    x: "0",
    xmlns: "http://www.w3.org/2000/svg",
    y: "0"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M65.261 76.833L13.167 76.833 13.167 24.739 44.511 24.739 53.428 15.823 4.25 15.823 4.25 85.75 74.177 85.75 74.177 36.572 65.261 45.489z",
                  fill: color,
                  stroke: color
                }), React.createElement("path", {
                  d: "M54.385 8.53L63.438 17.582 23.67 57.349 32.651 66.33 60.629 38.351 69.546 29.434 72.418 26.562 81.47 35.615 85.75 4.25z",
                  fill: color,
                  stroke: color
                }));
}

var Export = {
  make: Icons$Export
};

function Icons$Trash(Props) {
  var className = Props.className;
  var colorOpt = Props.color;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var color = colorOpt !== undefined ? colorOpt : "white";
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 24 24"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("path", {
                  d: "M3 6v18h18V6H3zm5 14a1 1 0 01-2 0V10a1 1 0 012 0v10zm5 0a1 1 0 01-2 0V10a1 1 0 012 0v10zm5 0a1 1 0 01-2 0V10a1 1 0 012 0v10zm4-18v2H2V2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2H22z",
                  fill: color,
                  stroke: color
                }));
}

var Trash = {
  make: Icons$Trash
};

function Icons$Prettier$Dark(Props) {
  var className = Props.className;
  var widthOpt = Props.width;
  var heightOpt = Props.height;
  var width = widthOpt !== undefined ? widthOpt : "24";
  var height = heightOpt !== undefined ? heightOpt : "24";
  var tmp = {
    height: height,
    width: width,
    viewBox: "0 0 210 210",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", {
                  fill: "none",
                  fillRule: "evenodd",
                  stroke: "none",
                  strokeWidth: "1"
                }, React.createElement("g", undefined, React.createElement("g", undefined, React.createElement("g", {
                              transform: "translate(0 200)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "150",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "70",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 180)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "160",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "130",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "40",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 160)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "100",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "110",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 140)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "140",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "100",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "30",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 120)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "170",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "60",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 100)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "90",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "80",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "30",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 80)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "190",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 60)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "190",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "60",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "120",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "70",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "40",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 40)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "30",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "180",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "20",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "150",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "50",
                                  fill: "#BF85BF",
                                  rx: "5",
                                  x: "90",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "80",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", {
                              transform: "translate(0 20)"
                            }, React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "170",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "110",
                                  fill: "#F7B93E",
                                  rx: "5",
                                  x: "50",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "40",
                                  fill: "#EA5E5E",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                })), React.createElement("g", undefined, React.createElement("rect", {
                                  height: "10",
                                  width: "70",
                                  fill: "#4D616E",
                                  opacity: "0.5",
                                  rx: "5",
                                  x: "140",
                                  y: "0"
                                }), React.createElement("rect", {
                                  height: "10",
                                  width: "130",
                                  fill: "#56B3B4",
                                  rx: "5",
                                  x: "0",
                                  y: "0"
                                }))))));
}

var Dark = {
  make: Icons$Prettier$Dark
};

var Prettier = {
  Dark: Dark
};

export {
  Play ,
  Inspect ,
  GraphQL ,
  PureScript ,
  TypeScript ,
  Export ,
  Trash ,
  Prettier ,
  
}
/* react Not a pure module */
